### ISSUE TITLE
 java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by Gordon2780** [RoleWong/tencent_cloud_chat_push#1]
E/AndroidRuntime( 9279): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 9279): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:431)
E/AndroidRuntime( 9279): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:277)
E/AndroidRuntime( 9279): 	at com.tencent.chat.flutter.push.tencent_cloud_chat_push.TencentCloudChatPushPlugin$3.onServiceCallback(TencentCloudChatPushPlugin.java:202)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.TIMPushService$4.a(TIMPushService.java:11)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.interfaces.TIMPushCallback.a(TIMPushCallback.java:2)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.impl.TIMPushServiceImpl$RegisterPushCallBack.a(TIMPushServiceImpl.java:3)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.interfaces.TIMPushCallback.a(TIMPushCallback.java:2)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.impl.TIMPushTokenRequester.a(TIMPushTokenRequester.java:17)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.impl.TIMPushTokenRequester.a(TIMPushTokenRequester.java:2)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.impl.TIMPushTokenRequester$1.a(TIMPushTokenRequester.java:9)
E/AndroidRuntime( 9279): 	at com.tencent.qcloud.tim.push.oempush.OEMPushSetting$1.onServiceCallback(OEMPushSetting.java:14)
E/AndroidRuntime( 9279): 	at com.tencent.timpush.fcm.TIMPushFCMService$1.run(TIMPushFCMService.java:2)
E/AndroidRuntime( 9279): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 9279): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9279): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 9279): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 9279): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 9279): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9279): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 9279): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/Process ( 9279): Sending signal. PID: 9279 SIG: 9

**Comment by RoleWong** [comment]
Hi Qin, this issue will be fixed in 7.9 version, which will be released in next week
