### ISSUE TITLE
registerPush注册推送后，用户自动退出登录

### ISSUE THREAD

**Issue by error-code** [RoleWong/tencent_cloud_chat_push#3]
目前逻辑如下：
1、TIMUIKitCore.getInstance().init(...); //初始化腾讯IM
2、TIMUIKitCore.getInstance().login(); //用户登录
----以上步骤之前正常使用，下面接入推送----------------------------------
3、TencentCloudChatPush().registerPush(...); //注册推送

只要执行第3步，腾讯IMSDK就自动退出登录

**Comment by RoleWong** [comment]
辛苦升级到最新的push插件版本试试呢? 理论上第三步是不会退出登录IM的

**Comment by error-code** [comment]
用的就是最新版本
```
  tencent_cloud_chat_uikit: 2.7.0                #腾讯IM
  tencent_cloud_chat_push: ^8.1.6906              #消息推送
```

**Comment by RoleWong** [comment]
registerPush应该使用独立特性功能，相当于重新登录了个账号

可以在 registerPush之前调用下 setRegistrationID 设置下登录的useid ，然后在registerPush

![企业微信截图_9b132096-a76e-4bf9-87ab-441744f5436e](https://github.com/user-attachments/assets/b039d070-2cf3-415e-820f-82fa03902c89)

**Comment by error-code** [comment]
感谢回复，重新登录问题解决了，但有了新问题
就是在线时，一直收到推送消息，而且消息是错误的，效果如下图：
![111](https://github.com/user-attachments/assets/dbaf83db-7727-458d-a90d-b39f06dfcc0c)
标题：null title

希望APP打开状态时，不要收到聊天消息推送
